name: CI

on:
  workflow_dispatch:
  push:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3 # Use up to 3 cpus to build juceaide, etc

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  BuildAndTest:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            binary: dummy.app/Contents/MacOS/dummy &
          - name: Windows
            os: windows-latest
            binary: START /B Debug/dummy.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure
        run: cmake -B Builds

      - name: Build
        run: cmake --build Builds --parallel 4

      - name: Run
        working-directory: Builds/dummy_artefacts
        timeout-minutes: 1
        run: |
          ls -ahl
          ${{ matrix.binary }} 

      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'
